version: '3.8'

services:
  mizcuin-api:
    build: 
      context: ./app
    container_name: mizcui_api
    ports:
      - "8080:40000"
    environment:
      - DB_PATH=/app/app/mizcuin.db
    restart: always